# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals pc

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Build and publish hello-world-master'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './hello-world-master/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/myapp'

- task: DotNetCoreCLI@2
  displayName: 'Build hello-world-master2'
  inputs:
    command: 'build'
    projects: './hello-world-master2/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Create subfolder and publish hello-world-master2'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Path "$(Build.ArtifactStagingDirectory)/myapp/folder1/subfolder" -ItemType Directory -Force
      dotnet publish ./hello-world-master2/*.csproj -c $(buildConfiguration) -o "$(Build.ArtifactStagingDirectory)/myapp/folder1/subfolder"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/myapp'
    artifactName: '.net-app'